openapi: 3.0.0
info:
  title: strip chat test task
  version: 1.0.0
tags:
  - name: statistics
    description: Статистика по странам
paths:
  /statistics/countries/inc:
    $ref: 'paths/statistics-countries-inc.yml'
  /statitstics/countries:
    $ref: 'paths/statistics-countries.yml'
