openapi: 3.0.0
info:
  title: strip chat test task
  version: 1.0.0
tags:
  - name: test1
    description: description1
paths:
  /tests:
    $ref: 'paths/tests.yml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
